networks:
  ch_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1

services:
  keeper1:
    build:
      context: .
      dockerfile: Dockerfile-ch
      args:
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    container_name: keeper1
    command: sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/keeper_config.xml
    volumes:
      #- ./ch-config-files/orquestration-config.d/keeper1/keeper_config.xml:/etc/clickhouse-server/keeper_config.xml
      - ./ch-config-files/orquestration-config.d/keeper1:/etc/clickhouse-server
      - ./data/keepers/1/log:/var/log/clickhouse-server
      #- ./data/keepers/1/db:/var/lib/clickhouse
      - ch-keeper1-data:/var/lib/clickhouse
    networks:
      ch_network:
        ipv4_address: 172.18.0.2

  keeper2:
    build:
      context: .
      dockerfile: Dockerfile-ch
      args:
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    container_name: keeper2
    command: sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/keeper_config.xml
    volumes:
      #- ./ch-config-files/orquestration-config.d/keeper2/keeper_config.xml:/etc/clickhouse-server/keeper_config.xml
      - ./ch-config-files/orquestration-config.d/keeper2:/etc/clickhouse-server
      - ./data/keepers/2/log:/var/log/clickhouse-server
      #- ./data/keepers/2/db:/var/lib/clickhouse
      - ch-keeper2-data:/var/lib/clickhouse
    networks:
      ch_network:
        ipv4_address: 172.18.0.3

  keeper3:
    build:
      context: .
      dockerfile: Dockerfile-ch
      args:
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    container_name: keeper3
    command: sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/keeper_config.xml
    volumes:
      #- ./ch-config-files/orquestration-config.d/keeper3/keeper_config.xml:/etc/clickhouse-server/keeper_config.xml
      - ./ch-config-files/orquestration-config.d/keeper3:/etc/clickhouse-server
      - ./data/keepers/3/log:/var/log/clickhouse-server
      #- ./data/keepers/3/db:/var/lib/clickhouse
      - ch-keeper3-data:/var/lib/clickhouse
    networks:
      ch_network:
        ipv4_address: 172.18.0.4

  ch-node1:
    build:
      context: .
      dockerfile: Dockerfile-ch
      args:
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    container_name: ch-node1
    command: sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml
    depends_on:
      - keeper1
      - keeper2
      - keeper3
    volumes:
      - ./data/nodes/1/log:/var/log/clickhouse-server
      - ch-node1-data:/var/lib/clickhouse
      #- ./data/nodes/1/db:/var/lib/clickhouse
      #- ./ch-config-files/node1/config.xml:/etc/clickhouse-server/config.xml
      - ./ch-config-files/node-config.d/node1/:/etc/clickhouse-server
      #- ./ch-config-files/access/default/:/var/lib/clickhouse/access
    networks:
      ch_network:
        ipv4_address: 172.18.0.5

  ch-node2:
    build:
      context: .
      dockerfile: Dockerfile-ch
      args:
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    container_name: ch-node2
    command: sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml
    depends_on:
      - keeper1
      - keeper2
      - keeper3
    volumes:
      - ./data/nodes/2/log:/var/log/clickhouse-server
      - ch-node2-data:/var/lib/clickhouse
      #- ./data/nodes/2/db:/var/lib/clickhouse
      #- ./ch-config-files/node2/config.xml:/etc/clickhouse-server/config.xml
      - ./ch-config-files/node-config.d/node2/:/etc/clickhouse-server
      #- ./ch-config-files/access/default/:/var/lib/clickhouse/access
    networks:
      ch_network:
        ipv4_address: 172.18.0.6

  ch-node3:
    build:
      context: .
      dockerfile: Dockerfile-ch
      args:
        CLICKHOUSE_VERSION: ${CLICKHOUSE_VERSION}
        UBUNTU_VERSION: ${UBUNTU_VERSION}
    container_name: ch-node3
    command: sudo -u clickhouse clickhouse-server --config-file=/etc/clickhouse-server/config.xml
    depends_on:
      - keeper1
      - keeper2
      - keeper3
    volumes:
      - ./data/nodes/3/log:/var/log/clickhouse-server
      - ch-node3-data:/var/lib/clickhouse
      #- ./data/nodes/3/db:/var/lib/clickhouse
      #- ./ch-config-files/node3/config.xml:/etc/clickhouse-server/config.xml
      - ./ch-config-files/node-config.d/node3/:/etc/clickhouse-server
      #- ./ch-config-files/access/default/:/var/lib/clickhouse/access
    networks:
      ch_network:
        ipv4_address: 172.18.0.7

  haproxy:
    image: haproxy:2.8
    container_name: haproxy
    ports:
      - "8126:8126"
      - "9003:9003"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./ssl-certificates/haproxy.pem:/usr/local/etc/haproxy/haproxy.pem:ro
    depends_on:
      - ch-node1
      - ch-node2
      - ch-node3
    networks:
      ch_network:
        ipv4_address: 172.18.0.8

  sqlserver_db:
    build:
      context: .
      dockerfile: Dockerfile-sqlserver
      args:
        SQLSERVER_VERSION: ${SQLSERVER_VERSION}
        MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    container_name: sqlserver_db
    networks:
      ch_network:
        ipv4_address: 172.18.0.9

volumes:
  ch-node1-data:
  ch-node2-data:
  ch-node3-data:
  ch-keeper1-data:
  ch-keeper2-data:
  ch-keeper3-data:
